# Generated by Django 4.1 on 2022-09-04 16:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('coursename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('year', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('coursestatus', models.IntegerField(choices=[(1, 'Open'), (0, 'Close')])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseCode', to='course.id')),
            ],
        ),
    ]
